import mongoose from "mongoose";

// Stores AI-generated fit report for one candidate against one employer job.
// Generated by the employer or triggered by Smart Talent Matching.
// Only accessible to the employer who owns the job (firebaseUid = employer's uid).

const candidateFitReportSchema = new mongoose.Schema(
  {
    // Employer who owns this report — never expose to other employers or the candidate
    employerFirebaseUid: { type: String, required: true, index: true },

    // The job this report was generated for
    jobId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "EmployerJob",
      required: true,
    },

    // The candidate being evaluated
    candidateFirebaseUid: { type: String, required: true },

    // Snapshot of the candidate's name and email at report generation time
    candidateName: { type: String, default: "" },
    candidateEmail: { type: String, default: "" },

    // 0–100 fit score produced by Azure AI
    matchScore: { type: Number, default: 0 },

    // Why the candidate is a good fit
    strengths: [{ type: String }],

    // Risk areas or missing requirements
    risks: [{ type: String }],

    // Evidence from projects and certifications supporting the match
    projectEvidence: [{ type: String }],

    // Skills from the JD that the candidate is missing
    missingRequirements: [{ type: String }],

    // "yes" | "no" | "maybe"
    shortlistRecommendation: {
      type: String,
      enum: ["yes", "no", "maybe"],
      default: "maybe",
    },

    // AI narrative summary explaining the recommendation
    summary: { type: String, default: "" },

    // Suggested interview questions tailored to this candidate's gaps
    interviewQuestions: [{ type: String }],
  },
  { timestamps: true }
);

const CandidateFitReport = mongoose.model("CandidateFitReport", candidateFitReportSchema);
export default CandidateFitReport;
