import mongoose from "mongoose";

// Stores AI Career Coach conversation history per user.
// Messages are ordered by createdAt for chat rendering.
// Each document belongs exclusively to one firebaseUid.

const chatMessageSchema = new mongoose.Schema(
  {
    // Owner — never expose one user's chat history to another
    firebaseUid: { type: String, required: true, index: true },

    // "user" = message typed by the candidate
    // "ai"   = response generated by Azure AI Career Coach
    role: { type: String, enum: ["user", "ai"], required: true },

    // The message content
    content: { type: String, required: true },

    // Optional: link to the Analysis document that provided context for this message
    analysisId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Analysis",
      default: null,
    },
  },
  { timestamps: true }
);

const ChatMessage = mongoose.model("ChatMessage", chatMessageSchema);
export default ChatMessage;
