import mongoose from "mongoose";

// Stores one mock interview session per document.
// Contains the generated questions, the user's answers, AI feedback, and readiness scores.

const questionSchema = new mongoose.Schema(
  {
    question: { type: String, default: "" },
    userAnswer: { type: String, default: "" },

    // AI feedback fields for this individual question
    score: { type: Number, default: 0 },           // 0–100
    strengths: [{ type: String }],
    weaknesses: [{ type: String }],
    improvedAnswer: { type: String, default: "" },
    tips: [{ type: String }],
  },
  { _id: false }
);

// Readiness score broken into six dimensions
const readinessScoreSchema = new mongoose.Schema(
  {
    technicalAccuracy: { type: Number, default: 0 },   // 0–100
    communication: { type: Number, default: 0 },
    projectExplanation: { type: Number, default: 0 },
    problemSolving: { type: Number, default: 0 },
    confidence: { type: Number, default: 0 },
    roleRelevance: { type: Number, default: 0 },
    overall: { type: Number, default: 0 },
  },
  { _id: false }
);

const mockInterviewSchema = new mongoose.Schema(
  {
    // Owner — never expose one user's interview results to another
    firebaseUid: { type: String, required: true, index: true },

    // The role the interview was generated for
    targetRole: { type: String, default: "" },

    // "general" | "technical" | "behavioural" | "jd-based"
    interviewType: { type: String, default: "general" },

    // Optional JD text used to generate role-specific questions
    jobDescription: { type: String, default: "" },

    // Questions generated by Azure AI, each with user answer + AI feedback
    questions: [questionSchema],

    // Composite readiness score across all six dimensions
    readinessScore: { type: readinessScoreSchema, default: () => ({}) },

    // "pending" until the user submits answers, then "completed"
    status: {
      type: String,
      enum: ["pending", "completed"],
      default: "pending",
    },
  },
  { timestamps: true }
);

const MockInterview = mongoose.model("MockInterview", mockInterviewSchema);
export default MockInterview;
